fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class:   App\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address: test@test.com
        sender_name: test
    registration:
        confirmation:
            enabled: true
    resetting:
        email:
            from_email:
                address:        resetting@example.com
                sender_name:    Demo Resetting